url=jdbc:postgresql://localhost:5432/library
username=postgres
password=mha1471
driver=org.postgresql.Driver
changeLogFile=src/main/resources/db/changelog/db.changelog-master.yaml
outputChangeLogFile=src/main/resources/db/changelog/initial.yaml